global:
  nodeSelectors:
    application: "application"
    database: "database"

redis:
  replicaCount: 1
  image:
    repository: redis
    tag: 7-alpine
    pullPolicy: IfNotPresent
  service:
    port: 6379
  resources:
    requests:
      cpu: "10m"
      memory: "16Mi"
    limits:
      cpu: "50m"
      memory: "64Mi"

postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: 15-alpine
    pullPolicy: IfNotPresent
  config:
    user: "postgres"
    db: "pingpongdb"
    port: 5432
  # this password is used for the demonstration purpose only.
  # In production, we have to use a more security tools like HashiCorp Vault or AWS Secrets Manager to manage the secrets.
  secret:
    password: "postgres"
  persistence:
    # storage class is set to empty string to use the default storage class of the cluster
    # If you want to use a specific storage class, you can set the value of storageClass to the name of the desired storage class like AWS EBS.
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 2Gi
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

pongService:
  replicaCount: 2
  image:
    repository: pong-service
    tag: latest
    pullPolicy: Never
  service:
    port: 8081
  resources:
    requests:
      cpu: "20m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
  hpa:
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532

pingService:
  replicaCount: 2
  image:
    repository: ping-service
    tag: latest
    pullPolicy: Never
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 30080
  resources:
    requests:
      cpu: "20m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
  hpa:
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
