apiVersion: v2
name: hepapi-case
description: Helm chart for Go Microservices (Ping-Pong) with PostgreSQL and Redis
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: pingService
    version: 0.1.0
    repository: "file://charts/ping-service"
  - name: pongService
    version: 0.1.0
    repository: "file://charts/pong-service"
  - name: redis
    version: 0.1.0
    repository: "file://charts/redis"
  - name: postgres
    version: 0.1.0
    repository: "file://charts/postgres"
