apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hepapi-case.fullname" . }}-ping-config
  labels:
    {{- include "hepapi-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: ping-service
data:
  PONG_SERVICE_URL: "http://{{ include "hepapi-case.fullname" . }}-pong-service:{{ .Values.pongService.service.port }}"
  PING_SERVICE_PORT: {{ .Values.pingService.service.port | quote }}