apiVersion: v1
kind: Service
metadata:
  name: {{ include "hepapi-case.fullname" . }}-ping-service
  labels:
    {{- include "hepapi-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: ping-service
spec:
  type: {{ .Values.pingService.service.type }}
  ports:
    - port: {{ .Values.pingService.service.port }}
      targetPort: {{ .Values.pingService.service.targetPort }}
      # The nodePort is set to 30080, which means that the service will be accessible on port 30080 of the nodes in the cluster.
      # It has vulnerabilities, so it should be used with caution.
      # In production, it's better to use a LoadBalancer or Ingress for external access.
      nodePort: {{ .Values.pingService.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "hepapi-case.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ping-service