apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-service-deployment
spec:
  # Resources managed by HPA, so we don't set replicas here. HPA will manage the number of replicas based on CPU utilization.
  # replicas: 2
  selector: 
    matchLabels:
      app: ping-service
  template:
    metadata:
      labels:
        app: ping-service
    spec:
      # Security context is set to run the container as a non-root user with a specific user ID (65532). 
      # This enhances security by preventing the container from running with root privileges.
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      nodeSelector:
        workload: application
      containers:
        - name: ping-service
          image: ping-service
          # non-root user is used to run the container (same as the Dockerfile)
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          # Image pull policy is set to "Never" to ensure that the local Docker image is used in Minikube.
          # This is useful for development and testing purposes, as it allows you to use the latest local build of the ping-service without pulling from a remote registry.
          imagePullPolicy: Never
          env:
            - name: PONG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ping-service-config
                  key: PONG_SERVICE_URL
            - name: PING_SERVICE_PORT
              valueFrom: 
                configMapKeyRef:
                  name: ping-service-config
                  key: PONG_SERVICE_PORT
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"        

          livenessProbe:
            httpGet:
              path: /healthz/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5