apiVersion: v1
kind: Service
metadata:
  name: {{ include "hepapi-case.fullname" . }}-redis-cache
  labels:
    {{- include "hepapi-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
      name: redis
  selector:
    {{- include "hepapi-case.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis