apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hepapi-case.fullname" . }}-redis-config
  labels:
    {{- include "hepapi-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
data:
  REDIS_PORT: {{ .Values.redis.service.port | quote }}