apiVersion: v1
kind: Service
metadata:
  name: {{ include "hepapi-case.fullname" . }}-pong-service
  labels:
    {{- include "hepapi-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: pong-service
spec:
  type: ClusterIP 
  ports:
    - port: {{ .Values.pongService.service.port }}
      targetPort: {{ .Values.pongService.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "hepapi-case.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pong-service