apiVersion: v1
kind: Service
metadata:
  name: pong-service
spec:
  type: ClusterIP # Sadece cluster içi erişim (Private Zone)
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: pong-service