nameSuffix: postgres
componentLabel: postgres
serviceResourceName: postgres

replicaCount: 1
image:
  repository: postgres
  tag: 15-alpine
  # IfNotPresent => The image will be pulled only if it is not already present on the node.
  pullPolicy: IfNotPresent
config:
  user: "postgres"
  db: "pingpongdb"
# this password is used for the demonstration purpose only.
# In production, we have to use a more security tools like HashiCorp Vault or AWS Secrets Manager to manage the secrets.
secret:
  password: "postgres"
persistence:
  # storageClass: null => Use the default storage class of the cluster (Dynamic Provisioning Enabled)
  # storageClass: ""   => Disable dynamic provisioning and default storage class (Static PV matching only)
  # storageClass: "gp3" => Use a specific storage class (e.g. AWS EBS)
  storageClass: null
  # ReadWriteOnce => The volume can be mounted as read-write by a single node.
  # ReadWriteMany => The volume can be mounted as read-write by many nodes. Pods on the different nodes can read and write to the same volume.
  accessMode: ReadWriteOnce
  size: 2Gi
service:
  type: ClusterIP
  port: 5432
  targetPort: 5432
  name: postgres
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "250m"
    memory: "512Mi"