apiVersion: v1
kind: Service
metadata:
  # the service name has to be the same as the docker-compose service name
  # if it is different, the application will not be able to connect to the database
  # because the DNSCore will not be able to resolve the service name to the correct IP address
  name: {{ include "hepapi-case.fullname" . }}-postgres
  labels:
    {{- include "hepapi-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.config.port }}
      targetPort: {{ .Values.postgres.config.port }}
      protocol: TCP
      name: postgres
  selector:
    {{- include "hepapi-case.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres