apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hepapi-case.fullname" . }}-{{ .Values.postgres.nameSuffix }}-secret
  labels:
    {{- include "hepapi-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.postgres.componentLabel }}
# The secret type is set to Opaque, which means that the secret data is arbitrary user-defined data. 
# In this case, it is used to store the PostgreSQL password.
type: Opaque
data:
  # The password is base64 encoded.
  # In production, we have to use a more security tools like HashiCorp Vault or AWS Secrets Manager to manage the secrets.
  POSTGRES_PASSWORD: {{ .Values.postgres.secret.password | b64enc | quote }}