apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hepapi-case.fullname" . }}-{{ .Values.postgres.nameSuffix }}-statefulset
  labels:
    {{- include "hepapi-case.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.postgres.componentLabel }}
spec:
  serviceName: {{ include "hepapi-case.fullname" . }}-{{ .Values.postgres.serviceResourceName }}
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      {{- include "hepapi-case.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.postgres.componentLabel }}
  template:
    metadata:
      labels:
        {{- include "hepapi-case.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.postgres.componentLabel }}
    spec:
      # Node affinity and tolerations are used to ensure that the PostgreSQL pods are scheduled on nodes that are designated for database workloads.
      # This helps in isolating the database from other workloads, improving performance and security.
      {{- if .Values.global.nodeSelectors.database }}
      affinity:
        nodeAffinity:
          # If there are no other Nodes in the environment that meet the tolerance, the Pod cannot schedule to the new Node.
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - {{ .Values.global.nodeSelectors.database }}
      # Only toleration doesn't guarantee that the pod will be scheduled on a node with the matching taint, but it allows the pod to be scheduled on such nodes if they are available.
      {{- end }}
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: {{ .Values.global.nodeSelectors.database | quote }}
          effect: "NoSchedule"
      containers:
        - name: {{ .Values.postgres.componentLabel }}
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
              name: {{ .Values.postgres.service.name }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "hepapi-case.fullname" . }}-{{ .Values.postgres.nameSuffix }}-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "hepapi-case.fullname" . }}-{{ .Values.postgres.nameSuffix }}-config
                  key: POSTGRES_USER
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "hepapi-case.fullname" . }}-{{ .Values.postgres.nameSuffix }}-config
                  key: POSTGRES_PORT
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "hepapi-case.fullname" . }}-{{ .Values.postgres.nameSuffix }}-secret
                  key: POSTGRES_PASSWORD
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          # Startup probe is configured to check the readiness of the PostgreSQL database before the application starts accepting traffic.
          # different from liveness and readiness probes, startup probes are used to determine if the application has started successfully.
          startupProbe:
            exec:
              command:
               - pg_isready
               - -U
               - postgres
            initialDelaySeconds: 5  
            periodSeconds: 5        
            timeoutSeconds: 3       
            failureThreshold: 30    

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.config.user | quote }}
                - -d
                - {{ .Values.postgres.config.db | quote }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.config.user | quote }}
                - -d
                - {{ .Values.postgres.config.db | quote }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes:
          - {{ .Values.postgres.persistence.accessMode }}
        # storageClassName is set to null to use the default storage class of the cluster
        {{- if not (kindIs "invalid" .Values.postgres.persistence.storageClass) }} 
        storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size | quote }}