name: Ping-Pong CI

on:
  workflow_dispatch:

jobs:
  # ==========================================
  test-services:
    name: Test (${{ matrix.service }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      # matrix allows us to run the same job for multiple services (ping-service and pong-service) in PARALLEL
      # run the same steps for each service, but in separate runners
      matrix:
        service: [ping-service, pong-service]
    steps:
      # Checkout the code from the repository to the runner's workspace
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.6
          # Use Go module caching to speed up builds and tests
          cache: true
          cache-dependency-path: |
            ${{ matrix.service }}/go.sum
            ${{ matrix.service }}/go.mod

      - name: Run go unit tests
        run: |
          cd ${{ matrix.service }}
          go test -v ./...

  # ==========================================
  lint-helm:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm CLI
        uses: azure/setup-helm@v3
        with:
          version: v3.17.0

        # Build Helm dependencies and run helm lint to validate the chart locally before pushing
      - name: Build Helm Dependencies
        run: |
          helm dependency build deployments

      - name: Lint Helm Charts
        run: |
          helm lint deployments
  # ==========================================
  security-scan:
    name: Native Security & CodeQL Scan
    needs: [test-services]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

        # DRA helps you identify and remediate known vulnerabilities in your dependencies.
        # It is recommended to run this action on pull requests to catch vulnerabilities before they are merged into the main branch.
      - name: Dependency Review (PR Check)
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v4
  # ==========================================
  build-and-push:
    name: Build and Push (${{ matrix.service }})
    needs: [test-services, lint-helm, security-scan]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
      matrix:
        service: [ping-service, pong-service]
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Metadata (tags, labels) for Docker
        # id: meta => This step generates metadata which can be used in subsequent steps.
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=,format=short

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Use GitHub Actions cache to speed up Docker builds by caching layers between builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
  ##helm package and push:
